# Generated by Django 3.1.5 on 2021-01-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_image',
            field=models.URLField(default=''),
        ),
    ]
